# Generated by Django 5.0.6 on 2024-06-19 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agroapp', '0002_deliveryboy_last_login_farmer_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryboy',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='last_login',
        ),
    ]
