# Generated by Django 5.0.6 on 2024-06-19 12:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroapp', '0004_deliveryboy_last_login_farmer_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryboy',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
