# Generated by Django 5.0.6 on 2024-06-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroapp', '0005_alter_deliveryboy_last_login_alter_farmer_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryboy',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
