# Generated by Django 5.0.6 on 2024-06-23 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agroapp', '0009_productcategory_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_price',
        ),
    ]
