# Generated by Django 5.0.6 on 2024-07-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroapp', '0011_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='start_date',
            field=models.DateField(),
        ),
    ]
