# Generated by Django 5.0.6 on 2024-07-24 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroapp', '0013_cartworker'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboy',
            name='supplier',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='agroapp.supplier'),
            preserve_default=False,
        ),
    ]
