# Generated by Django 5.0.6 on 2024-07-30 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agroapp', '0014_deliveryboy_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryboy',
            name='supplier',
        ),
    ]
