# Generated by Django 5.0.6 on 2024-07-31 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroapp', '0017_order_cart_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agroapp.cartitem'),
        ),
    ]
