# Generated by Django 5.0.6 on 2024-08-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroapp', '0019_remove_order_cart_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
