# Generated by Django 5.0.6 on 2024-08-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroapp', '0021_order_delivery_boy_alter_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
