# Generated by Django 5.0.6 on 2024-08-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroapp', '0026_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
