# Generated by Django 5.0.6 on 2024-08-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroapp', '0027_product_is_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
