# Generated by Django 5.0.6 on 2024-08-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroapp', '0028_productcategory_is_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboy',
            name='reasontoblock',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='reasontoblock',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='reasontoblock',
            field=models.TextField(blank=True, null=True),
        ),
    ]
