# Generated by Django 5.0.6 on 2024-08-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroapp', '0029_deliveryboy_reasontoblock_farmer_reasontoblock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('rented', 'Rented')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('rented', 'Rented')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('rented', 'Rented')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('rented', 'Rented')], default='pending', max_length=20),
        ),
    ]
