# Generated by Django 5.0.6 on 2024-08-18 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroapp', '0030_alter_order_delivery_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(editable=False, max_length=100)),
                ('product_name', models.CharField(editable=False, max_length=255)),
                ('quantity', models.PositiveIntegerField(editable=False)),
                ('damage_level', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=20)),
                ('damage_type', models.CharField(choices=[('physical', 'Physical'), ('operational', 'Operational'), ('wear_and_tear', 'Wear and Tear')], max_length=20)),
                ('damage_photos', models.FileField(blank=True, null=True, upload_to='return_photos/')),
                ('estimated_repair_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='agroapp.order')),
            ],
        ),
    ]
