# Generated by Django 5.0.6 on 2024-08-16 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroapp', '0030_alter_order_delivery_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_description', models.TextField()),
                ('payment_for_defect', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dispute_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agroapp.order')),
            ],
        ),
    ]
