# Generated by Django 5.0.6 on 2024-08-18 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroapp', '0031_returnrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDamage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_level', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=20)),
                ('damage_type', models.CharField(choices=[('physical', 'Physical'), ('operational', 'Operational'), ('wear_and_tear', 'Wear and Tear')], max_length=20)),
                ('estimated_repair_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damages', to='agroapp.product')),
            ],
        ),
    ]
