# Generated by Django 5.0.6 on 2024-08-22 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agroapp', '0033_returnrequest_total_repair_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnrequest',
            name='damage_photos',
        ),
    ]
