# Generated by Django 5.0.6 on 2024-08-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroapp', '0034_remove_returnrequest_damage_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
