# Generated by Django 5.0.6 on 2024-08-22 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agroapp', '0035_returnrequest_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnrequest',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='razorpay_signature',
        ),
    ]
